Repository IT-Cotato/10th-T-LINK-BE, pull requests merged in 2025-02, with the labels that each got.

#57 feat [#56] 회원 탈퇴 API 구현
  src/main/java/org/cotato/tlinkserver/api/controller/UserController.java
  src/main/java/org/cotato/tlinkserver/api/facade/UserFacade.java
  src/main/java/org/cotato/tlinkserver/auth/ReissueService.java
  src/main/java/org/cotato/tlinkserver/domain/user/application/UserService.java
Labels: ✨ feat, 🐬 치현

#60 Feat [#52] 과외방 관련 구현
  src/main/java/org/cotato/tlinkserver/api/controller/RoomController.java
  src/main/java/org/cotato/tlinkserver/api/facade/RoomFacade.java
  src/main/java/org/cotato/tlinkserver/domain/room/LessonDay.java
  src/main/java/org/cotato/tlinkserver/domain/room/Registration.java
  src/main/java/org/cotato/tlinkserver/domain/room/Room.java
  src/main/java/org/cotato/tlinkserver/domain/room/application/RegistrationService.java
  src/main/java/org/cotato/tlinkserver/domain/room/application/RoomService.java
  src/main/java/org/cotato/tlinkserver/domain/room/application/dto/request/.gitkeep
  src/main/java/org/cotato/tlinkserver/domain/room/application/dto/request/PermissionRequest.java
  src/main/java/org/cotato/tlinkserver/domain/room/application/dto/request/RoomRequest.java
  src/main/java/org/cotato/tlinkserver/domain/room/application/dto/response/.gitkeep
  src/main/java/org/cotato/tlinkserver/domain/room/application/dto/response/LessonDayModifyResponse.java
  src/main/java/org/cotato/tlinkserver/domain/room/application/dto/response/OpponentResponse.java
  src/main/java/org/cotato/tlinkserver/domain/room/application/dto/response/PermissionResponse.java
  src/main/java/org/cotato/tlinkserver/domain/room/application/dto/response/RoomDataResponse.java
  src/main/java/org/cotato/tlinkserver/domain/room/application/dto/response/RoomModifyResponse.java
  src/main/java/org/cotato/tlinkserver/domain/room/application/dto/response/RoomResponse.java
  src/main/java/org/cotato/tlinkserver/domain/room/application/dto/response/RoomsResponse.java
  src/main/java/org/cotato/tlinkserver/domain/room/application/dto/response/ShareCodeResponse.java
  src/main/java/org/cotato/tlinkserver/domain/room/constant/DayOfWeek.java
  src/main/java/org/cotato/tlinkserver/domain/room/infra/repository/.gitkeep
  src/main/java/org/cotato/tlinkserver/domain/room/infra/repository/RegistrationRepository.java
  src/main/java/org/cotato/tlinkserver/domain/room/infra/repository/RoomRepository.java
  src/main/java/org/cotato/tlinkserver/domain/user/User.java
  src/main/java/org/cotato/tlinkserver/global/common/BaseResponse.java
  src/main/java/org/cotato/tlinkserver/global/util/ApiResponseUtil.java
  src/main/java/org/cotato/tlinkserver/global/util/RandomUtil.java
Labels: ✨ feat, 🦭 영찬

#72 feat [#71] 캘린더 정보 조회 API 구현
  src/main/java/org/cotato/tlinkserver/api/controller/RoomController.java
  src/main/java/org/cotato/tlinkserver/api/dto/response/RoomInfoDetailLessonDayResponse.java
  src/main/java/org/cotato/tlinkserver/api/dto/response/RoomInfoDetailResponse.java
  src/main/java/org/cotato/tlinkserver/api/dto/response/RoomInfoResponse.java
  src/main/java/org/cotato/tlinkserver/api/facade/RoomFacade.java
  src/main/java/org/cotato/tlinkserver/api/facade/dto/response/RoomInfoDTO.java
  src/main/java/org/cotato/tlinkserver/api/facade/dto/response/RoomInfoDetailDTO.java
  src/main/java/org/cotato/tlinkserver/api/facade/dto/response/RoomInfoDetailLessonDayDTO.java
  src/main/java/org/cotato/tlinkserver/domain/room/application/RegistrationService.java
  src/main/java/org/cotato/tlinkserver/domain/room/infra/repository/RegistrationRepository.java
Labels: ✨ feat, 🐬 치현

#81 refactor [#80] User 엔티티의 backgroundColor 값 제거
  src/main/java/org/cotato/tlinkserver/api/dto/request/OnboardRequest.java
  src/main/java/org/cotato/tlinkserver/api/dto/response/UserProfileResponse.java
  src/main/java/org/cotato/tlinkserver/api/facade/dto/response/UserProfileDTO.java
  src/main/java/org/cotato/tlinkserver/auth/command/OnboardCommand.java
  src/main/java/org/cotato/tlinkserver/domain/room/application/dto/response/OpponentResponse.java
  src/main/java/org/cotato/tlinkserver/domain/user/User.java
Labels: ♻️ refactor, 🐬 치현

#85 Feat [#84] 숙제 수정을 위한 상세 조회 시 사용자에 따라 숙제 파일을 다르게 조회
  src/main/java/org/cotato/tlinkserver/api/controller/HomeworkController.java
  src/main/java/org/cotato/tlinkserver/api/facade/HomeworkFacade.java
Labels: ✨ feat, 🦭 영찬

#87 Refactor [#84] 요일 반환 형식 통일
  src/main/java/org/cotato/tlinkserver/api/controller/RoomController.java
  src/main/java/org/cotato/tlinkserver/api/dto/response/RoomLessonDayResponse.java
  src/main/java/org/cotato/tlinkserver/api/facade/RoomFacade.java
  src/main/java/org/cotato/tlinkserver/api/facade/dto/request/RoomLessonDayDTO.java
  src/main/java/org/cotato/tlinkserver/domain/room/application/dto/request/RoomModifyRequest.java
  src/main/java/org/cotato/tlinkserver/domain/room/application/dto/request/RoomSaveRequest.java
  src/main/java/org/cotato/tlinkserver/domain/room/application/dto/response/RoomResponse.java
Labels: ♻️ refactor, 🦭 영찬

#95 refactor [#94] API 명세에 지정된 값을 반환하도록 @JsonValue 어노테이션 추가
  src/main/java/org/cotato/tlinkserver/domain/counselingLog/constant/Engagement.java
  src/main/java/org/cotato/tlinkserver/domain/room/constant/DayOfWeek.java
  src/main/java/org/cotato/tlinkserver/domain/user/constant/Gender.java
  src/main/java/org/cotato/tlinkserver/domain/user/constant/Role.java
Labels: ♻️ refactor, 🐬 치현

#96 Refactor [#93] 요일 반환 시 ID 제거
  src/main/java/org/cotato/tlinkserver/domain/room/application/dto/response/LessonDayModifyResponse.java
Labels: ♻️ refactor, 🦭 영찬

#98 refactor [#97] 프론트 요청으로 역할 Enum(Role) 값 수정
  src/main/java/org/cotato/tlinkserver/domain/user/constant/Role.java
Labels: ♻️ refactor, 🐬 치현

#101 feat [#99] 캘린더 정보 조회 API 응답 값에 subject 값 추가
  src/main/java/org/cotato/tlinkserver/api/dto/response/RoomInfoDetailResponse.java
  src/main/java/org/cotato/tlinkserver/api/facade/dto/response/RoomInfoDetailDTO.java
Labels: ✨ feat, 🐬 치현

#102 Feat [#100] 공유 코드로 입장 전, 확인을 위해 선생님 정보 반환
  src/main/java/org/cotato/tlinkserver/api/controller/RoomController.java
  src/main/java/org/cotato/tlinkserver/api/dto/RoomJoinResponse.java
  src/main/java/org/cotato/tlinkserver/api/facade/RoomFacade.java
Labels: ✨ feat, 🦭 영찬

#106 Refactor [#103] 사용자에 따른 과외방 이름 전달
  src/main/java/org/cotato/tlinkserver/domain/room/application/dto/response/RoomResponse.java
Labels: ♻️ refactor, 🦭 영찬

#108 Refactor [#105] 과외 수정 상세 조회 학생 및 학부모 권한 추가
  src/main/java/org/cotato/tlinkserver/api/controller/RoomController.java
Labels: ♻️ refactor, 🦭 영찬

#110 Refactor [#109] 과외방 수정을 위한 상세 조회는 선생님만 할 수 있도록 수정
  src/main/java/org/cotato/tlinkserver/api/controller/RoomController.java
Labels: ♻️ refactor, 🦭 영찬

#116 Refactor [#115] 공유 코드를 통한 선생님 조회 트랜잭션 어노테이션 추가
  src/main/java/org/cotato/tlinkserver/api/facade/RoomFacade.java
Labels: ♻️ refactor, 🦭 영찬

#118 Fix [#117] 과외방 삭제 시 잘못된 삭제 방법 수정
  src/main/java/org/cotato/tlinkserver/api/facade/RoomFacade.java
  src/main/java/org/cotato/tlinkserver/domain/room/application/RoomService.java
Labels: 🦭 영찬, 🔨 fix

#120 refactor [#119] 권한 변수명 변경
  src/main/java/org/cotato/tlinkserver/api/dto/response/RoomDetailPermissionResponse.java
  src/main/java/org/cotato/tlinkserver/api/dto/response/RoomDetailResponse.java
Labels: ♻️ refactor, 🐬 치현

#122 Refactor [#121] 초대창 변경으로 인한 제공 정보 수정
  src/main/java/org/cotato/tlinkserver/api/dto/RoomJoinResponse.java
  src/main/java/org/cotato/tlinkserver/api/facade/RoomFacade.java
Labels: ♻️ refactor, 🦭 영찬

#124 Fix [#123] 회원 탈퇴 시, Registration이 삭제되는 문제 해결
  src/main/java/org/cotato/tlinkserver/domain/room/Registration.java
  src/main/java/org/cotato/tlinkserver/domain/user/User.java
Labels: 🦭 영찬, 🔨 fix

#129 Refactor [#128] 성적 조회에서 ID 추가
  src/main/java/org/cotato/tlinkserver/domain/gradeStatistic/application/dto/response/ExamResponse.java
Labels: ♻️ refactor, 🦭 영찬

#130 docs [#125] 리드미 작성
  README.md
Labels: 🐬 치현, 📄 docs
