Repository IT-Cotato/10th-T-LINK-BE, pull requests merged in 2025-01, with the labels that each got.

#2 Init [#1] 기초 프로젝트 세팅
  .gitattributes
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/cotato/tlinkserver/TlinkServerApplication.java
  src/test/java/org/cotato/tlinkserver/TlinkServerApplicationTests.java
Labels: ✅ chore, ☁️ db, 🐬 치현

#4 File [#3] 패키지 구조 생성
  src/main/java/org/cotato/tlinkserver/annotation/.gitkeep
  src/main/java/org/cotato/tlinkserver/api/controller/.gitkeep
  src/main/java/org/cotato/tlinkserver/api/dto/request/.gitkeep
  src/main/java/org/cotato/tlinkserver/api/dto/response/.gitkeep
  src/main/java/org/cotato/tlinkserver/api/facade/.gitkeep
  src/main/java/org/cotato/tlinkserver/api/vo/.gitkeep
  src/main/java/org/cotato/tlinkserver/auth/filter/.gitkeep
  src/main/java/org/cotato/tlinkserver/auth/jwt/.gitkeep
  src/main/java/org/cotato/tlinkserver/domain/model/application/dto/request/.gitkeep
  src/main/java/org/cotato/tlinkserver/domain/model/application/dto/response/.gitkeep
  src/main/java/org/cotato/tlinkserver/domain/model/infra/repository/.gitkeep
  src/main/java/org/cotato/tlinkserver/global/config/.gitkeep
  src/main/java/org/cotato/tlinkserver/global/exception/.gitkeep
  src/main/java/org/cotato/tlinkserver/global/util/.gitkeep
Labels: 🐬 치현, 📁 file

#6 File [#5] 기본 Security 및 CORS 설정
  src/main/java/org/cotato/tlinkserver/global/config/.gitkeep
  src/main/java/org/cotato/tlinkserver/global/config/CorsConfig.java
  src/main/java/org/cotato/tlinkserver/global/config/SecurityConfig.java
Labels: ✨ feat, 🐬 치현

#10 Chore [#9] Dockerfile 추가
  Dockerfile
Labels: ✅ chore, 🐬 치현, 📁 file

#14 Chore [#13] CD 파일에 production 환경 추가
  .github/workflows/workflow-main.yml
Labels: ✅ chore, 🐬 치현

#23 Hotfix [#22] S3 yml 키 값 재설정
  src/main/java/org/cotato/tlinkserver/global/util/S3FileHandler.java
Labels: 🐬 치현, 🔥 !hotfix

#30 Chore [#29] model 템플릿 폴더 삭제
  src/main/java/org/cotato/tlinkserver/domain/model/application/dto/request/.gitkeep
  src/main/java/org/cotato/tlinkserver/domain/model/application/dto/response/.gitkeep
  src/main/java/org/cotato/tlinkserver/domain/model/infra/repository/.gitkeep
Labels: ✅ chore, 🐬 치현

#33 Fix [#32] cloud 폴더 경로 지정
  .github/workflows/workflow-main.yml
  build.gradle
Labels: 🐬 치현, 🔨 fix

#34 Refactor [#31] ERD 변경에 따른 엔티티 정보 수정
  src/main/java/org/cotato/tlinkserver/domain/counselingLog/CounselingLog.java
  src/main/java/org/cotato/tlinkserver/domain/homework/Homework.java
  src/main/java/org/cotato/tlinkserver/domain/homework/HomeworkFile.java
  src/main/java/org/cotato/tlinkserver/domain/homework/HomeworkFileId.java
  src/main/java/org/cotato/tlinkserver/domain/room/LessonDay.java
  src/main/java/org/cotato/tlinkserver/domain/room/Registration.java
  src/main/java/org/cotato/tlinkserver/domain/room/Room.java
  src/main/java/org/cotato/tlinkserver/domain/room/RoomPermission.java
  src/main/java/org/cotato/tlinkserver/domain/user/User.java
Labels: ♻️ refactor, 🦭 영찬, 📁 file

#47 Refactor [#46] 요일 상세 메세지 수정
  src/main/java/org/cotato/tlinkserver/domain/room/constant/DayOfWeek.java
Labels: ♻️ refactor, 🦭 영찬

#49 docs 리펙토링 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/refactor-request.md
Labels: 📄 docs

#51 Refactor [#50] 공통 응답 핸들러 추상화
  src/main/java/org/cotato/tlinkserver/api/controller/FileTestController.java
  src/main/java/org/cotato/tlinkserver/api/controller/LectureFileBoxController.java
  src/main/java/org/cotato/tlinkserver/api/dto/response/BaseResponse.java
  src/main/java/org/cotato/tlinkserver/api/dto/response/DataResponse.java
  src/main/java/org/cotato/tlinkserver/api/dto/response/ErrorResponse.java
  src/main/java/org/cotato/tlinkserver/global/common/BaseResponse.java
  src/main/java/org/cotato/tlinkserver/global/exception/ConflictException.java
  src/main/java/org/cotato/tlinkserver/global/exception/GlobalExceptionHandler.java
  src/main/java/org/cotato/tlinkserver/global/exception/HttpRequestMethodNotSupportedException.java
  src/main/java/org/cotato/tlinkserver/global/exception/MethodArgumentTypeMismatchException.java
  src/main/java/org/cotato/tlinkserver/global/exception/NotFoundException.java
  src/main/java/org/cotato/tlinkserver/global/exception/TLinkException.java
  src/main/java/org/cotato/tlinkserver/global/exception/UnauthorizedException.java
  src/main/java/org/cotato/tlinkserver/global/message/ErrorMessage.java
  src/main/java/org/cotato/tlinkserver/global/message/SuccessMessage.java
  src/main/java/org/cotato/tlinkserver/global/util/ApiResponseUtil.java
  src/main/java/org/cotato/tlinkserver/global/util/ErrorMessage.java
  src/main/java/org/cotato/tlinkserver/global/util/SuccessMessage.java
Labels: ♻️ refactor
